### ISSUE TITLE
Test Task partitions with TaskLauncher

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-yarn#32]
As a developer, I'd like to test the Task partitions on an YARN cluster.

**Comment by jvalkeal** [comment]
Postponing to future as we're going to need spring-cloud-task 1.0.2.

**Comment by jvalkeal** [comment]
ok, going to close this as we got partitioned task working with task 1.1.x. Sample is in https://github.com/jvalkeal/randomstuff/blob/master/partitioned-batch-job.
